# Generated by Django 5.1.2 on 2025-06-05 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='ecommerce.team'),
        ),
    ]
