# Generated by Django 5.1.2 on 2025-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default='teams/default.png', upload_to='teams'),
        ),
    ]
